// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PilotSim.Data;

#nullable disable

namespace PilotSim.Data.Migrations
{
    [DbContext(typeof(SimDbContext))]
    partial class SimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PilotSim.Data.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CallsignPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("callsign_prefix");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<int?>("CruiseSpeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cruise_speed");

                    b.Property<string>("EngineType")
                        .HasColumnType("TEXT")
                        .HasColumnName("engine_type");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("manufacturer");

                    b.Property<string>("MsfsModelMatchCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("msfs_model_match_code");

                    b.Property<string>("MsfsTitle")
                        .HasColumnType("TEXT")
                        .HasColumnName("msfs_title");

                    b.Property<int?>("SeatCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seat_capacity");

                    b.Property<int?>("ServiceCeiling")
                        .HasColumnType("INTEGER")
                        .HasColumnName("service_ceiling");

                    b.Property<bool>("SupportsSimConnect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_simconnect");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("WakeCategory")
                        .HasColumnType("TEXT")
                        .HasColumnName("wake_category");

                    b.HasKey("Id");

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Airport", b =>
                {
                    b.Property<string>("Icao")
                        .HasColumnType("TEXT")
                        .HasColumnName("icao");

                    b.Property<string>("AppFreq")
                        .HasColumnType("TEXT")
                        .HasColumnName("app_freq");

                    b.Property<string>("AtisFreq")
                        .HasColumnType("TEXT")
                        .HasColumnName("atis_freq");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Major")
                        .HasColumnName("category");

                    b.Property<int?>("ElevationFt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("elevation_ft");

                    b.Property<string>("FuelTypes")
                        .HasColumnType("TEXT")
                        .HasColumnName("fuel_types");

                    b.Property<string>("GroundFreq")
                        .HasColumnType("TEXT")
                        .HasColumnName("ground_freq");

                    b.Property<bool>("HasFuel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("has_fuel");

                    b.Property<bool>("HasMaintenance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("has_maintenance");

                    b.Property<double?>("Lat")
                        .HasColumnType("REAL")
                        .HasColumnName("lat");

                    b.Property<double?>("Lon")
                        .HasColumnType("REAL")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("TEXT")
                        .HasColumnName("operating_hours");

                    b.Property<string>("TowerFreq")
                        .HasColumnType("TEXT")
                        .HasColumnName("tower_freq");

                    b.HasKey("Icao");

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Airspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AssociatedAirport")
                        .HasColumnType("TEXT")
                        .HasColumnName("associated_airport");

                    b.Property<string>("BoundaryJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("boundary_json");

                    b.Property<double?>("CenterLat")
                        .HasColumnType("REAL")
                        .HasColumnName("center_lat");

                    b.Property<double?>("CenterLon")
                        .HasColumnType("REAL")
                        .HasColumnName("center_lon");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("class");

                    b.Property<string>("Frequency")
                        .HasColumnType("TEXT")
                        .HasColumnName("frequency");

                    b.Property<int?>("LowerAltitude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lower_altitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("TEXT")
                        .HasColumnName("operating_hours");

                    b.Property<double?>("RadiusNm")
                        .HasColumnType("REAL")
                        .HasColumnName("radius_nm");

                    b.Property<string>("Restrictions")
                        .HasColumnType("TEXT")
                        .HasColumnName("restrictions");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int?>("UpperAltitude")
                        .HasColumnType("INTEGER")
                        .HasColumnName("upper_altitude");

                    b.HasKey("Id");

                    b.ToTable("airspace", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.AirspaceNotice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AirspaceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("airspace_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT")
                        .HasColumnName("effective_to");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AirspaceId");

                    b.ToTable("airspace_notice", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Metric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("K")
                        .HasColumnType("TEXT")
                        .HasColumnName("k");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.Property<string>("TUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("t_utc");

                    b.Property<double?>("V")
                        .HasColumnType("REAL")
                        .HasColumnName("v");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("metric", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.PilotProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("AssignedFrequency")
                        .HasColumnType("TEXT")
                        .HasColumnName("assigned_frequency");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("callsign");

                    b.Property<string>("CertificatesRatings")
                        .HasColumnType("TEXT")
                        .HasColumnName("certificates_ratings");

                    b.Property<double?>("CurrentAltitude")
                        .HasColumnType("REAL")
                        .HasColumnName("current_altitude");

                    b.Property<double?>("CurrentHeading")
                        .HasColumnType("REAL")
                        .HasColumnName("current_heading");

                    b.Property<double?>("CurrentLatitude")
                        .HasColumnType("REAL")
                        .HasColumnName("current_latitude");

                    b.Property<double?>("CurrentLongitude")
                        .HasColumnType("REAL")
                        .HasColumnName("current_longitude");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_phase");

                    b.Property<double?>("CurrentSpeed")
                        .HasColumnType("REAL")
                        .HasColumnName("current_speed");

                    b.Property<string>("ExperienceLevel")
                        .HasColumnType("TEXT")
                        .HasColumnName("experience_level");

                    b.Property<string>("FlightPlan")
                        .HasColumnType("TEXT")
                        .HasColumnName("flight_plan");

                    b.Property<bool>("IsLive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_live");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update");

                    b.Property<string>("PilotName")
                        .HasColumnType("TEXT")
                        .HasColumnName("pilot_name");

                    b.Property<string>("PreferredAirports")
                        .HasColumnType("TEXT")
                        .HasColumnName("preferred_airports");

                    b.Property<string>("SimConnectStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("simconnect_status");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.ToTable("pilot_profile", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Runway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("airport_icao");

                    b.Property<string>("Ident")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ident");

                    b.Property<bool>("Ils")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ils");

                    b.Property<int?>("LengthM")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_m");

                    b.Property<int?>("MagneticHeading")
                        .HasColumnType("INTEGER")
                        .HasColumnName("magnetic_heading");

                    b.HasKey("Id");

                    b.HasIndex("AirportIcao");

                    b.ToTable("runway", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AirportIcao")
                        .HasColumnType("TEXT")
                        .HasColumnName("airport_icao");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty");

                    b.Property<string>("InitialStateJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("initial_state_json");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("RubricJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("rubric_json");

                    b.Property<int?>("Seed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("seed");

                    b.HasKey("Id");

                    b.HasIndex("AirportIcao");

                    b.ToTable("scenario", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Difficulty")
                        .HasColumnType("TEXT")
                        .HasColumnName("difficulty");

                    b.Property<string>("EndedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("ended_utc");

                    b.Property<string>("Outcome")
                        .HasColumnType("TEXT")
                        .HasColumnName("outcome");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("parameters_json");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scenario_id");

                    b.Property<int>("ScoreTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("score_total");

                    b.Property<string>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.TrafficProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AircraftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aircraft_id");

                    b.Property<string>("AirportIcao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("airport_icao");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("callsign");

                    b.Property<string>("FlightType")
                        .HasColumnType("TEXT")
                        .HasColumnName("flight_type");

                    b.Property<double>("FrequencyWeight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1.0)
                        .HasColumnName("frequency_weight");

                    b.Property<string>("Route")
                        .HasColumnType("TEXT")
                        .HasColumnName("route");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("AirportIcao");

                    b.ToTable("traffic_profile", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.Turn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AtcJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("atc_json");

                    b.Property<int?>("Idx")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idx");

                    b.Property<string>("InstructorJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("instructor_json");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_id");

                    b.Property<string>("TtsAudioPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("tts_audio_path");

                    b.Property<string>("UserAudioPath")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_audio_path");

                    b.Property<string>("UserTranscript")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_transcript");

                    b.Property<string>("Verdict")
                        .HasColumnType("TEXT")
                        .HasColumnName("verdict");

                    b.Property<string>("StartedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_utc");

                    b.Property<int?>("SttMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stt_ms");

                    b.Property<int?>("InstructorMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("instructor_ms");

                    b.Property<int?>("AtcMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("atc_ms");

                    b.Property<int?>("TtsMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("tts_ms");

                    b.Property<int?>("TotalMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_ms");

                    b.Property<int?>("ScoreDelta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("score_delta");

                    b.Property<bool>("Blocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("blocked");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("turn", (string)null);
                });

            modelBuilder.Entity("PilotSim.Data.Models.AirspaceNotice", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Airspace", "Airspace")
                        .WithMany("Notices")
                        .HasForeignKey("AirspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airspace");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Metric", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Session", "Session")
                        .WithMany("Metrics")
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PilotSim.Data.Models.PilotProfile", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Aircraft", "Aircraft")
                        .WithMany("PilotProfiles")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Runway", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Airport", "Airport")
                        .WithMany("Runways")
                        .HasForeignKey("AirportIcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Scenario", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Airport", "Airport")
                        .WithMany("Scenarios")
                        .HasForeignKey("AirportIcao");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Session", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Scenario", "Scenario")
                        .WithMany("Sessions")
                        .HasForeignKey("ScenarioId");

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("PilotSim.Data.Models.TrafficProfile", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Aircraft", "Aircraft")
                        .WithMany("TrafficProfiles")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PilotSim.Data.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportIcao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Turn", b =>
                {
                    b.HasOne("PilotSim.Data.Models.Session", "Session")
                        .WithMany("Turns")
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Aircraft", b =>
                {
                    b.Navigation("PilotProfiles");

                    b.Navigation("TrafficProfiles");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Airport", b =>
                {
                    b.Navigation("Runways");

                    b.Navigation("Scenarios");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Airspace", b =>
                {
                    b.Navigation("Notices");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Scenario", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("PilotSim.Data.Models.Session", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
